CREATE TABLE `collection_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`territoryId` int NOT NULL,
	`period` varchar(7) NOT NULL,
	`collectedAt` timestamp NOT NULL DEFAULT (now()),
	`collectionType` enum('news','structured','full') NOT NULL DEFAULT 'full',
	`newsCount` int NOT NULL DEFAULT 0,
	`ibamaEmbargoCount` int NOT NULL DEFAULT 0,
	`ibamaAutoCount` int NOT NULL DEFAULT 0,
	`ibgeCensoCount` int NOT NULL DEFAULT 0,
	`ibgeRendimentoCount` int NOT NULL DEFAULT 0,
	`inpeDeterCount` int NOT NULL DEFAULT 0,
	`inpeProdesCount` int NOT NULL DEFAULT 0,
	`anaHidroCount` int NOT NULL DEFAULT 0,
	`anaOutorgaCount` int NOT NULL DEFAULT 0,
	`queiroDiarioCount` int NOT NULL DEFAULT 0,
	`rawData` json,
	`totalSignals` int NOT NULL DEFAULT 0,
	`notes` text,
	CONSTRAINT `collection_snapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `index_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`territoryId` int NOT NULL,
	`period` varchar(7) NOT NULL,
	`snapshotId` int,
	`itt` float,
	`ics` float,
	`ivs` float,
	`ive` float,
	`ici` float,
	`stt` float,
	`ittDelta` float,
	`icsDelta` float,
	`ivsDelta` float,
	`iveDelta` float,
	`iciDelta` float,
	`sttDelta` float,
	`activatedIndex` varchar(10),
	`scenario` enum('estabilidade','pressao','escalada'),
	`signalCount` int DEFAULT 0,
	`relevantSignalCount` int DEFAULT 0,
	`keyEvents` json,
	`llmRationale` text,
	`source` enum('llm','manual','import') NOT NULL DEFAULT 'llm',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `index_history_id` PRIMARY KEY(`id`)
);
